# -*- coding: utf-8 -*-
"""Python_basics_01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pYlhzMqdtyiMN1qTqIbjNj4Wg4xG0Q3y

##Introduction

###If we increase the no.of hastags then the font size will decrease and vice versa
"""

# This is Comment
# There are two types of comments in python
#    1. Single Line Comment
#    2. Multi Line Comment

# To Print something in Python

'''
This is a python print function
Print is a keyword in python
print should have
'''



print ("Course")
print ("Hello World")

print ('Hello World')

# Variable means that tends to change
a = 3 #means that assigning a value 3 to variable "a"
Name = "Brand"
Age = 32
print (Name)
print (Age)

Tata_Steel = 32300
Adani_Enterprises = 18226
Bharti_Airtel = 79800

print (f"The Capex Plans in FY23 and FY24 of Tata Steel is {Tata_Steel}; Adani Enterprises is {Adani_Enterprises} and Bharti Airtel is {Bharti_Airtel}")

# Here "f" is f-string and it lets us use palceholder expressions to display strings

Tata_Steel = 32300
Adani_Enterprises = 18226
Bharti_Airtel = 79800

print (f"The Capex Plans in FY23 and FY24 of Tata Steel is {Tata_Steel}; Adani Enterprises is {Adani_Enterprises} and Bharti Airtel is {Bharti_Airtel}")

# If we want to print x,y,z same values

x = y = z = "Brand"

print(x)
print(y)
print(z)

